### ISSUE TITLE
Question about result file

### ISSUE THREAD

**Issue by zhaokai5** [javier2491/FaceQnet#22]
Hi, thanks for your greate job, I'm ready to use your scores_quality_VGGFace2_*.txt as label to train my own quality assignment network, but i found most of face score are smaller than 0.6, is this normal?  I also check VGGFace dateset and found some face image worth higer socre.

**Comment by javier-hernandezo** [comment]
Hello, thanks for your interest in working with FaceQnet! 

The absolute values ofthe quality scores may vary due to the normalization used. This time I have used the same normalization function (and parameters) to obtain the scores for ALL the datasets (VGGFace2, LFW, CyberExtruder, and Biosecure). Due to that the quality scores of each individual dataset are not ocuppying the whole [0,1] range. It is totally normal.

You can use the scores as they are or you can apply a normalization function to adjust them to your desired range before training your QA network.

Regards,

**Comment by zhaokai5** [comment]
Thanks for your reply, I understand this problem.

For anthor queasion, I found some images only one face, but scores_quality_VGGFace2_*.txt has two score, shown in follow image, does it due to face detect algorithm?
![image](https://user-images.githubusercontent.com/24264343/133576206-d58cb4ef-f635-4c49-b4a0-869aeebcb2c9.png)

**Comment by javier-hernandezo** [comment]
Yes, indeed. Those duplicates are due to the face detector. It sometimes has false detections. In these cases I recommend you to discard all the images except the first one, that use to be the good one (not always, but quite often).

**Comment by zhaokai5** [comment]
Ok, great appreciate for your help, THANKS!
